In [4]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    l=numpy.array(arr,float)
    m=l[-1::-1]
    return m

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

2 3 4 5 6 7 8
[8. 7. 6. 5. 4. 3. 2.]


In [7]:
import numpy
numbers=input().strip().split(" ")
arr=numpy.array(numbers,int)
print(numpy.reshape(arr,(3,3)))

1 2 3 4 5 6 7 8 9 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
import numpy
n,m=map(int,input().strip().split(" "))
arr=numpy.array(input().strip().split(" "),int)
arr=arr.reshape(n,m)
print(numpy.transpose(arr))
print(arr.flatten())

2 2 
1 2 3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [14]:
import numpy
n,m,p=map(int,input().strip().split(" "))
arr1=numpy.array([input().split()],int).reshape(n,p)
arr2=numpy.array([input().split()],int).reshape(m,p)
print(numpy.concatenate((arr1,arr2),axis=0))

4 3 2
1 2 1 2 1 2 1 2
3 4 3 4 3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [15]:
import numpy
tup=tuple(map(int,input().strip().split(" ")))
print(numpy.zeros(tup,int))
print(numpy.ones(tup,int)) 

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [18]:
import numpy
n,m=map(int,input().split())
for m in range(n):
    a=numpy.array([input().split(" ")],int)
for m in range(n):
    b=numpy.array([input().split(" ")],int)
print(numpy.add(a,b))
print(numpy.subtract(a,b))
print(numpy.multiply(a,b))
print(numpy.floor_divide(a,b))
print(numpy.mod(a,b))
print(numpy.power(a,b))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [25]:
import numpy
numpy.set_printoptions(legacy='1.13')
numbers=input().strip().split(" ")
my_arr=numpy.array(numbers,float)
print(numpy.floor(my_arr))
print(numpy.ceil(my_arr))
print(numpy.rint(my_arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [27]:
import numpy
n,m=map(int,input().strip().split(" "))
arr=numpy.array([input().split()],int).reshape(n,m)
p=numpy.sum(arr,axis=0)
print(numpy.prod(p))

2 2
1 2 3 4
24


In [28]:
import numpy
n,m=map(int,input().strip().split(" "))
arr=numpy.array([input().split()],int).reshape(n,m)
m=numpy.min(arr,axis=1)
print(numpy.max(m))

4 2
2 5 3 7 1 3 4 0
3


In [30]:
import numpy
n,m=map(int,input().strip().split(" "))
arr=numpy.array([input().split()],int).reshape(n,m)
print(numpy.mean(arr,axis=1))
print(numpy.var(arr,axis=0))
print(numpy.std(arr))

2 2
1 2 3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [46]:
import numpy
n=int(input())
for m in range(n-1):
    a=numpy.array([input().split()],int).reshape(n,n)
for m in range(n-1):
    b=numpy.array([input().split()],int).reshape(n,n)
print(numpy.dot(a,b))

2
1 2 3 4
1 2 3 4
[[ 7 10]
 [15 22]]


In [47]:
import numpy
a= numpy.array(input().strip().split(" "),int)
b= numpy.array(input().strip().split(" "),int)
print(numpy.inner(a,b))
print(numpy.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


In [48]:
import numpy
p=list(map(float,input().strip().split(" ")))
x=float(input())
print(numpy.polyval(p,x))

1.1 2 3
0
3.0


In [49]:
import numpy
n=int(input())
for m in range(n-1):
    a=numpy.array([input().split()],float).reshape(n,n)
print(round(numpy.linalg.det(a),2))

2
1.1 1.1 1.1 1.1
0.0
